//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityZone
    {
        public int TID { get; set; }
        public int CityID { get; set; }
        public int ZoneID { get; set; }
    
        public virtual City City { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
