//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompititorInfo
    {
        public int CompititorInfoID { get; set; }
        public int RetailerID { get; set; }
        public int SaleOfficerID { get; set; }
        public Nullable<int> SylabusID { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual Sylabu Sylabu { get; set; }
        public virtual SaleOfficer SaleOfficer { get; set; }
        public virtual Retailer Retailer { get; set; }
    }
}
