//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dealer()
        {
            this.DealerCityAreas = new HashSet<DealerCityArea>();
            this.DealerRanges = new HashSet<DealerRanx>();
            this.JobsDetails = new HashSet<JobsDetail>();
            this.Retailers = new HashSet<Retailer>();
            this.DelieveryBoys = new HashSet<DelieveryBoy>();
            this.DispatchInVanMasters = new HashSet<DispatchInVanMaster>();
            this.Tbl_RSMSummary = new HashSet<Tbl_RSMSummary>();
        }
    
        public int TID { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string DealerCode { get; set; }
        public Nullable<int> RegionalHeadID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<bool> Planned { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public int SaleOfficerID { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Location { get; set; }
        public Nullable<int> DistributorClass { get; set; }
        public string Email { get; set; }
        public string Picture1 { get; set; }
        public string Remarks { get; set; }
        public string ShopName { get; set; }
        public string CNIC { get; set; }
        public string NewArea { get; set; }
        public Nullable<int> RangeID { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealerCityArea> DealerCityAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealerRanx> DealerRanges { get; set; }
        public virtual RegionalHead RegionalHead { get; set; }
        public virtual Region Region { get; set; }
        public virtual SaleOfficer SaleOfficer { get; set; }
        public virtual Zone Zone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobsDetail> JobsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Retailer> Retailers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DelieveryBoy> DelieveryBoys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispatchInVanMaster> DispatchInVanMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RSMSummary> Tbl_RSMSummary { get; set; }
    }
}
