//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerDispatchCalculation
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> Display { get; set; }
        public Nullable<decimal> Balanceamount1 { get; set; }
        public Nullable<decimal> Scheme { get; set; }
        public Nullable<decimal> Balanceamount2 { get; set; }
        public Nullable<decimal> WSDiscount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<int> DealerID { get; set; }
        public string BillNo { get; set; }
    }
}
