//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchInVan
    {
        public int ID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> RetailerID { get; set; }
        public Nullable<int> SOID { get; set; }
        public Nullable<int> DispatchQuantityinVan { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<bool> CreatedOn { get; set; }
        public Nullable<System.DateTime> InvoicedDate { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public Nullable<int> DelieveryboyID { get; set; }
        public Nullable<System.DateTime> FromDateOnInvoiced { get; set; }
        public Nullable<System.DateTime> ToDateOnInvoiced { get; set; }
        public Nullable<int> DispatchInVanMasterID { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Retailer Retailer { get; set; }
        public virtual SaleOfficer SaleOfficer { get; set; }
    }
}
