//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobsHistory
    {
        public int ID { get; set; }
        public Nullable<int> SoRetailerJobID { get; set; }
        public int JobID { get; set; }
        public Nullable<int> SaleOfficerID { get; set; }
        public Nullable<int> DealerID { get; set; }
        public int RetailerID { get; set; }
        public Nullable<int> PainterID { get; set; }
        public string JobType { get; set; }
        public Nullable<bool> SAvailable { get; set; }
        public Nullable<int> SQuantity1KG { get; set; }
        public Nullable<int> SQuantity5KG { get; set; }
        public Nullable<bool> SNewOrder { get; set; }
        public Nullable<int> SNewQuantity1KG { get; set; }
        public Nullable<int> SNewQuantity5KG { get; set; }
        public Nullable<int> SPreviousOrder1KG { get; set; }
        public Nullable<int> SPreviousOrder5KG { get; set; }
        public Nullable<bool> SPOSMaterialAvailable { get; set; }
        public string SImage { get; set; }
        public string SNote { get; set; }
        public Nullable<bool> PUseWC { get; set; }
        public Nullable<int> PUseWC1KG { get; set; }
        public Nullable<int> PUseWC5KG { get; set; }
        public Nullable<bool> PNewOrder { get; set; }
        public Nullable<int> PNewOrder1KG { get; set; }
        public Nullable<int> PNewOrder5KG { get; set; }
        public Nullable<bool> PNewLead { get; set; }
        public Nullable<int> PNewLead1KG { get; set; }
        public Nullable<int> PNewLead5KG { get; set; }
        public string PNewLeadMobNo { get; set; }
        public string PRemarks { get; set; }
        public string BShop { get; set; }
        public string BOldHouse { get; set; }
        public string BNewHouse { get; set; }
        public string BParking { get; set; }
        public string BPlazaBasement { get; set; }
        public string BFactoryArea { get; set; }
        public string BMosque { get; set; }
        public string BOthers { get; set; }
        public Nullable<bool> BLead { get; set; }
        public string BRemarks { get; set; }
        public string BLocationName { get; set; }
        public Nullable<bool> BSampleApplied { get; set; }
        public Nullable<System.DateTime> VisitedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Retailer Retailer { get; set; }
    }
}
