//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIReport
    {
        public int ID { get; set; }
        public Nullable<int> SOID { get; set; }
        public Nullable<int> TotalVisits { get; set; }
        public Nullable<int> ProductiveVisits { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual SaleOfficer SaleOfficer { get; set; }
    }
}
