//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagersLoginHst
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string MacAddress { get; set; }
        public string IPAddress { get; set; }
        public string ReportType { get; set; }
        public string ReportName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
