//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailersForApproval
    {
        public int TID { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string RetailerCode { get; set; }
        public string CNIC { get; set; }
        public string AccountNo { get; set; }
        public string CardNumber { get; set; }
        public string BankName { get; set; }
        public Nullable<int> DealerID { get; set; }
        public Nullable<int> SaleOfficerID { get; set; }
        public string ShopName { get; set; }
        public string Location { get; set; }
        public string LocationName { get; set; }
        public string LocationMargin { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string LandLineNo { get; set; }
        public string Market { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string Address { get; set; }
        public string RetailerType { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<int> Action { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string BankName2 { get; set; }
        public string AccountNo2 { get; set; }
    }
}
