//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOAttendance
    {
        public int ID { get; set; }
        public Nullable<int> SOID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> DealerID { get; set; }
        public Nullable<decimal> MarketStartLat { get; set; }
        public Nullable<decimal> MarketStartLong { get; set; }
        public string MarketStartLatlong { get; set; }
        public Nullable<decimal> MarketCloseLat { get; set; }
        public Nullable<decimal> MarketCloseLong { get; set; }
        public string MarketCloseLatlong { get; set; }
    
        public virtual City City { get; set; }
        public virtual Region Region { get; set; }
        public virtual SaleOfficer SaleOfficer { get; set; }
    }
}
