//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CurrentStock
    {
        public int ID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> Carton { get; set; }
        public Nullable<int> Danda { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> FinalValue { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Job Job { get; set; }
    }
}
