//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SOREGIONS
    {
        public int ID { get; set; }
        public int RegionID { get; set; }
        public int SaleofficerID { get; set; }
        public Nullable<int> RegionalHeadID { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
