//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CompititorBrand
    {
        public int ID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> PRCarton { get; set; }
        public Nullable<int> PRDanda { get; set; }
        public Nullable<int> PRGhatta { get; set; }
        public Nullable<int> SRCarton { get; set; }
        public Nullable<int> SRDanda { get; set; }
        public Nullable<int> SRGhatta { get; set; }
        public Nullable<int> SourceOfPurchase { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Brandname { get; set; }
        public Nullable<int> JobID { get; set; }
        public string ProdAvailability { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> PurchaseFinalValue { get; set; }
        public Nullable<decimal> SaleFinalValue { get; set; }
        public string Availability { get; set; }
    }
}
