//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MasterStock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MasterStock()
        {
            this.tbl_StockDetail = new HashSet<tbl_StockDetail>();
        }
    
        public int ID { get; set; }
        public int DistributorID { get; set; }
        public int SaleOfficerID { get; set; }
        public int RegionalHeadID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Createdby { get; set; }
    
        public virtual RegionalHead RegionalHead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_StockDetail> tbl_StockDetail { get; set; }
        public virtual SaleOfficer SaleOfficer { get; set; }
        public virtual Retailer Retailer { get; set; }
    }
}
